name: ODBC Scanner
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          python -m pip install --user clang_format==11.0.1
          python ./resources/scripts/format.py --check 

  duckdb-linux-amd64:
    name: DuckDB Linux (amd64)
    runs-on: ubuntu-latest
    needs: format-check
    env:
      GEN: ninja
      DUCKDB_AVAILABLE: 1
      INT_CAST_AVAILABLE: 1
      DUCKDB_ODBC_LIB_PATH: ${{ github.workspace }}/odbc/libduckdb_odbc.so
      DUCKDB_SHARED_LIB_PATH: ${{ github.workspace }}/libduckdb/libduckdb.so
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Install Dependencies
        run: |
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            unixodbc-dev \
            ninja-build

      - name: Download Shared Libs
        run: |
          mkdir odbc
          pushd odbc
          curl --no-progress-meter -LO https://github.com/duckdb/duckdb-odbc/releases/latest/download/duckdb_odbc-linux-amd64.zip
          unzip -q duckdb_odbc-linux-amd64.zip
          ls -laR
          popd
          mkdir libduckdb
          pushd libduckdb
          curl --no-progress-meter -LO https://github.com/duckdb/duckdb/releases/latest/download/libduckdb-linux-amd64.zip
          unzip -q libduckdb-linux-amd64.zip
          ls -laR
          popd

      - name: Configure
        run: |
          make configure

      - name: Build
        run: |
          make release

      - name: Setup ODBC Env
        run: |
          ./resources/scripts/write_odbcinst_ini.sh DuckDB "${DUCKDB_ODBC_LIB_PATH}"

      - name: C API Tests
        run: |
          make test_c_api

      - name: SQL Tests
        run: |
          make test

  duckdb-osx-aarch64:
    name: DuckDB MacOS (aarch64)
    runs-on: macos-latest
    needs: duckdb-linux-amd64
    env:
      GEN: ninja
      DUCKDB_AVAILABLE: 1
      INT_CAST_AVAILABLE: 1
      DUCKDB_ODBC_LIB_PATH: ${{ github.workspace }}/odbc/libduckdb_odbc.dylib
      DUCKDB_SHARED_LIB_PATH: ${{ github.workspace }}/libduckdb/libduckdb.dylib
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Install Dependencies
        run: |
          brew install \
            unixodbc \
            ninja

      - name: Download Shared Libs
        run: |
          mkdir odbc
          pushd odbc
          curl --no-progress-meter -LO https://github.com/duckdb/duckdb-odbc/releases/latest/download/duckdb_odbc-osx-universal.zip
          unzip -q duckdb_odbc-osx-universal.zip
          ls -laR
          popd
          ./resources/scripts/macos_update_downloaded_lib.sh ${DUCKDB_ODBC_LIB_PATH}
          mkdir libduckdb
          pushd libduckdb
          curl --no-progress-meter -LO https://github.com/duckdb/duckdb/releases/latest/download/libduckdb-osx-universal.zip
          unzip -q libduckdb-osx-universal.zip
          ls -laR
          popd

      - name: Configure
        run: |
          make configure

      - name: Build
        run: |
          make release

      - name: Setup ODBC Env
        run: |
          ./resources/scripts/write_odbcinst_ini.sh DuckDB "${DUCKDB_ODBC_LIB_PATH}"

      - name: C API Tests
        run: |
          make test_c_api

      - name: SQL Tests
        run: |
          make test

  mssql-linux-amd64:
    name: MSSQL Linux (amd64)
    runs-on: ubuntu-latest
    needs: duckdb-linux-amd64
    env:
      GEN: ninja
      MSSQL_AVAILABLE: 1
      INT_CAST_AVAILABLE: 1
      DUCKDB_SHARED_LIB_PATH: ${{ github.workspace }}/libduckdb/libduckdb.so
      ODBC_CONN_STRING_NODB: Driver={MSSQL Driver};Server=tcp:127.0.0.1,1433;UID=sa;PWD=P@ssword2;TrustServerCertificate=yes;
      ODBC_CONN_STRING: Driver={MSSQL Driver};Server=tcp:127.0.0.1,1433;UID=sa;PWD=P@ssword2;TrustServerCertificate=yes;Database=odbcscanner_test_db;
      MSSQL_ODBC_LIB_PATH: /opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.5.so.1.1
      ACCEPT_EULA: 1
      MSSQL_SA_PASSWORD: P@ssword2
      MSSQL_PID: Developer
      MSSQL_IP_ADDRESS: 127.0.0.1
      MSSQL_TCP_PORT: 1433
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Install
        run: |
          curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --batch --yes --dearmor -o /usr/share/keyrings/microsoft-prod.gpg
          curl -sSL https://packages.microsoft.com/config/ubuntu/24.04/mssql-server-preview.list | sudo tee /etc/apt/sources.list.d/mssql-server-preview.list
          curl -sSL -O https://packages.microsoft.com/config/ubuntu/24.04/packages-microsoft-prod.deb
          sudo dpkg -i packages-microsoft-prod.deb
          sudo apt-get update -y -q -o=Dpkg::Use-Pty=0
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            msodbcsql18 \
            mssql-server \
            ninja-build \
            python3-pyodbc \
            unixodbc-dev
          sudo -E /opt/mssql/bin/mssql-conf -n setup
          systemctl status mssql-server
          cat /etc/odbcinst.ini
          ./resources/scripts/write_odbcinst_ini.sh MSSQL "${MSSQL_ODBC_LIB_PATH}"

      - name: Prepare DB
        run: |
          python3 ./resources/scripts/prepare_test_db.py --dbms MSSQL --conn-str "${ODBC_CONN_STRING_NODB}"

      - name: CAPI Shared Lib
        run: |
          mkdir libduckdb
          pushd libduckdb
          curl --no-progress-meter -LO https://github.com/duckdb/duckdb/releases/latest/download/libduckdb-linux-amd64.zip
          unzip -q libduckdb-linux-amd64.zip
          ls -laR
          popd

      - name: Build
        run: |
          make configure
          make release

      - name: C API Tests
        run: |
          make test_c_api

      - name: SQL Tests
        run: |
          make test

  postgres-linux-amd64:
    name: PostgreSQL Linux (amd64)
    runs-on: ubuntu-latest
    needs: duckdb-linux-amd64
    env:
      GEN: ninja
      POSTGRES_AVAILABLE: 1
      INT_CAST_AVAILABLE: 1
      DUCKDB_SHARED_LIB_PATH: ${{ github.workspace }}/libduckdb/libduckdb.so
      ODBC_CONN_STRING_NODB: Driver={PostgreSQL Driver};Server=127.0.0.1;Port:1433;Username=postgres;Password=postgres;
      ODBC_CONN_STRING: Driver={PostgreSQL Driver};Server=127.0.0.1;Port:1433;Username=postgres;Password=postgres;Database=odbcscanner_test_db;
      POSTGRES_ODBC_LIB_PATH: /usr/lib/x86_64-linux-gnu/odbc/psqlodbcw.so
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Install
        run: |
          sudo apt-get update -y -q -o=Dpkg::Use-Pty=0
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            postgresql \
            odbc-postgresql \
            ninja-build \
            python3-pyodbc \
            unixodbc-dev
          sudo systemctl start postgresql
          sudo systemctl status postgresql
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres'"
          cat /etc/odbcinst.ini
          ./resources/scripts/write_odbcinst_ini.sh PostgreSQL "${POSTGRES_ODBC_LIB_PATH}"

      - name: Prepare DB
        run: |
          python3 ./resources/scripts/prepare_test_db.py --dbms PostgreSQL --conn-str "${ODBC_CONN_STRING_NODB}"

      - name: CAPI Shared Lib
        run: |
          mkdir libduckdb
          pushd libduckdb
          curl --no-progress-meter -LO https://github.com/duckdb/duckdb/releases/latest/download/libduckdb-linux-amd64.zip
          unzip -q libduckdb-linux-amd64.zip
          ls -laR
          popd

      - name: Build
        run: |
          make configure
          make release

      - name: C API Tests
        run: |
          make test_c_api

      - name: SQL Tests
        run: |
          make test

  mariadb-linux-amd64:
    name: MariaDB Linux (amd64)
    runs-on: ubuntu-latest
    needs: duckdb-linux-amd64
    env:
      GEN: ninja
      MYSQL_AVAILABLE: 1
      DUCKDB_SHARED_LIB_PATH: ${{ github.workspace }}/libduckdb/libduckdb.so
      ODBC_CONN_STRING_NODB: Driver={MariaDB Driver};SERVER=127.0.0.1;PORT=3306;USER=root;PASSWORD=root;
      ODBC_CONN_STRING: Driver={MariaDB Driver};SERVER=127.0.0.1;PORT=3306;USER=root;PASSWORD=root;DATABASE=odbcscanner_test_db;
      MARIADB_ODBC_LIB_PATH: /usr/lib/x86_64-linux-gnu/odbc/libmaodbc.so
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Install
        run: |
          sudo apt-get update -y -q -o=Dpkg::Use-Pty=0
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            mariadb-server \
            odbc-mariadb \
            ninja-build \
            python3-pyodbc \
            unixodbc-dev
          sudo systemctl start mariadb
          sudo systemctl status mariadb
          sudo mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('root'); FLUSH PRIVILEGES;"
          cat /etc/odbcinst.ini
          ./resources/scripts/write_odbcinst_ini.sh MariaDB "${MARIADB_ODBC_LIB_PATH}"

      - name: Prepare DB
        run: |
          python3 ./resources/scripts/prepare_test_db.py --dbms MariaDB --conn-str "${ODBC_CONN_STRING_NODB}"

      - name: CAPI Shared Lib
        run: |
          mkdir libduckdb
          pushd libduckdb
          curl --no-progress-meter -LO https://github.com/duckdb/duckdb/releases/latest/download/libduckdb-linux-amd64.zip
          unzip -q libduckdb-linux-amd64.zip
          ls -laR
          popd

      - name: Build
        run: |
          make configure
          make release

      - name: C API Tests
        run: |
          make test_c_api

      - name: SQL Tests
        run: |
          make test

  # currently using MySQL ODBC driver with MariaDB server
  mysql-linux-amd64:
    name: MySQL Linux (amd64)
    runs-on: ubuntu-latest
    needs: duckdb-linux-amd64
    env:
      GEN: ninja
      MYSQL_AVAILABLE: 1
      DUCKDB_SHARED_LIB_PATH: ${{ github.workspace }}/libduckdb/libduckdb.so
      ODBC_CONN_STRING_NODB: Driver={MySQL Driver};SERVER=127.0.0.1;PORT=3306;USER=root;PASSWORD=root;
      ODBC_CONN_STRING: Driver={MySQL Driver};SERVER=127.0.0.1;PORT=3306;USER=root;PASSWORD=root;DATABASE=odbcscanner_test_db;
      MYSQL_ODBC_LIB_PATH: /usr/lib/x86_64-linux-gnu/odbc/libmyodbc9w.so
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Install
        run: |
          sudo apt-get update -y -q -o=Dpkg::Use-Pty=0
          curl -LO https://dev.mysql.com/get/mysql-apt-config_0.8.34-1_all.deb
          sudo -E apt install -y -q -o=Dpkg::Use-Pty=0 ./mysql-apt-config_0.8.34-1_all.deb
          sudo apt-get update -y -q -o=Dpkg::Use-Pty=0
          sudo apt-get install -y -q -o=Dpkg::Use-Pty=0 \
            mysql-connector-odbc \
            mariadb-server \
            ninja-build \
            python3-pyodbc \
            unixodbc-dev
          sudo systemctl start mariadb
          sudo systemctl status mariadb
          sudo mysql -u root -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('root'); FLUSH PRIVILEGES;"
          cat /etc/odbcinst.ini
          ./resources/scripts/write_odbcinst_ini.sh MySQL "${MYSQL_ODBC_LIB_PATH}"

      - name: Prepare DB
        run: |
          python3 ./resources/scripts/prepare_test_db.py --dbms MySQL --conn-str "${ODBC_CONN_STRING_NODB}"

      - name: CAPI Shared Lib
        run: |
          mkdir libduckdb
          pushd libduckdb
          curl --no-progress-meter -LO https://github.com/duckdb/duckdb/releases/latest/download/libduckdb-linux-amd64.zip
          unzip -q libduckdb-linux-amd64.zip
          ls -laR
          popd

      - name: Build
        run: |
          make configure
          make release

      - name: C API Tests
        run: |
          make test_c_api

      # todo
      # - name: SQL Tests
      #  run: |
      #    make test
