name: ODBC Scanner
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'
      - run: |
          python3 -m pip install --user clang_format==11.0.1
          make format-check
  
  linux-amd64:
    name: Linux (amd64)
    runs-on: ubuntu-latest
    needs: format-check
    env:
      DUCKDB_ODBC_SHARED_LIB_PATH: ${{ github.workspace }}/odbc/libduckdb_odbc.so
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Setup ODBC env
        shell: bash
        run: |
          mkdir odbc
          cd odbc
          curl -LO https://github.com/duckdb/duckdb-odbc/releases/download/v1.3.2.0/duckdb_odbc-linux-amd64.zip
          unzip duckdb_odbc-linux-amd64.zip
          sudo apt install unixodbc-dev
          echo "[DuckDB Driver]" > ~/.odbcinst.ini
          echo "Driver = ${DUCKDB_ODBC_SHARED_LIB_PATH}" >> ~/.odbcinst.ini

      - name: Build and Test
        shell: bash
        run: |
          make configure
          make test_debug
